Issue 133 - License page edits
thegooddocsproject/website-hugo pull request #135
Opened 2022-03-04 00:08 UTC by netsaml

Converted gerunds to imperative verbs.

2022-03-04 00:15 UTC, barbaricyawps requested changes

2022-03-04 00:15 UTC, barbaricyawps commented on content/en/licenses.md
> +That way, others can also benefit from our project as you are. :smile:
Let's convert that back to the old school emoji. I guess Hugo doesn't render it, which makes me sad!

2022-03-04 00:16 UTC, barbaricyawps requested changes

2022-03-04 00:16 UTC, barbaricyawps commented on content/en/licenses.md
> +That way, others can also benefit from our project as you are. :smile:
```suggestion
That way, others can also benefit from our project as you are. :)
```

2022-03-04 00:19 UTC, deanna-cs commented
PR looks great!

2022-03-04 00:19 UTC, barbaricyawps approved these changes

2022-03-04 00:19 UTC, deanna-cs approved these changes

2022-03-04 00:19 UTC, barbaricyawps commented
@netsaml , thanks for making those changes! Congratulations on your first pull request!

2022-03-04 00:19 UTC, merged

2022-03-08 04:42 UTC, zivbk1 commented on content/en/licenses.md
> +That way, others can also benefit from our project as you are. :smile:
> Let's convert that back to the old school emoji. I guess Hugo doesn't render it, which makes me sad!

Hugo should render emojis.