Fixed verbiage on page
thegooddocsproject/website-hugo pull request #142
Opened 2022-03-15 22:47 UTC by Begster

I fixed grammar/verbiage on main landing page.

2022-03-16 14:26 UTC, barbaricyawps requested changes
Hi, @Begster ! These changes are great! I just have a few minor suggestions. Take a look and let me know what you think about them!

2022-03-16 14:26 UTC, barbaricyawps commented on content/en/_index.md
> +Every project deserves a minimum level of Good Docs, but it can be hard to know where to start or write.
**Suggestion (grammar, non-blocking):** Maybe let's remove the capitalization on "Good Docs" since we're not using the project name in this context and it wouldn't be grammatically correct to capitalize it otherwise.

2022-03-16 19:16 UTC, Begster commented on content/en/_index.md
> +Every project deserves a minimum level of Good Docs, but it can be hard to know where to start or write.
Yes, I will.

2022-03-16 19:28 UTC, Begster commented on content/en/_index.md
> +We describe our reasoning, referencing available research, to help writers decide when to deviate from suggestions.
Hi, Alyssa. I modified your sentence as shown below. Please let me know what you think. I don't have the command of the language and grammar you have, nor do I have the experience. I got this advice from Grammarly, which I understand does not have the market cornered on written English. :) Your advice will also help me in my future in tech wiring. Thanks!!

**MODIFIED:**
"We describe our reasoning and provide research to empower writers and non-writers alike to understand the deeper concepts and principles of effective technical writing."

2022-03-16 23:57 UTC, barbaricyawps commented on content/en/_index.md
> +We describe our reasoning, referencing available research, to help writers decide when to deviate from suggestions.
That's a great revision, @Begster . Let's go with that!

2022-03-17 13:51 UTC, Begster commented on content/en/_index.md
> +We describe our reasoning, referencing available research, to help writers decide when to deviate from suggestions.
Great! Thanks for reviewing, Alyssa!

2022-03-17 16:38 UTC, barbaricyawps approved these changes
@Begster , these changes look great! Approved!

2022-03-17 16:38 UTC, merged