Add glossaries working group
thegooddocsproject/website-hugo pull request #58
Opened 2021-04-21 16:50 UTC by barbaricyawps

## Purpose / why

Add the glossaries working group to the working group page.

## What changes were made?

New working group page for glossaries.

2021-04-21 16:54 UTC, bwklein approved these changes
Looks good to me.
https://deploy-preview-58--gdp-hugo.netlify.app/working-group/glossaries/

2021-04-23 02:16 UTC, camerons requested changes
A few suggested changes.

2021-04-23 02:16 UTC, camerons commented on content/en/working-group/glossaries.md
> +notesURL: https://docs.google.com/document/d/1Fjrl34ErnYammel9WmvXJ3rMWFANjoSiiGyyNSYOXUg/
```suggestion
notesURL: https://docs.google.com/document/d/1yzncnQB7uYktPnAQ4DqZYVPDdYnqDrWmqHzcpXrjkPg/
```
I think this is supposed to reference our meeting notes page, as per above.

2021-04-23 02:16 UTC, camerons commented on content/en/working-group/glossaries.md
> +We plan to use the base template (a "template of templates") that we've created as the starting point to create a template for glossaries. We will also create a process for a central glossary owner t
```suggestion
* We plan to use the base template (a "template of templates") that we've created as the starting point to create a template for glossaries.
* We will establish processes for sharing terms between organizations and glossaries.
* We will create a process for a central glossary owner to accept, triage, and refine proposals for new terms from their community.
```
Adding in the use case of sharing terms between organizations.

2021-04-23 02:16 UTC, camerons commented on content/en/working-group/glossaries.md
> +meeting: Monthly on Tuesdays at 7AM UTC(on Google Meet)
```suggestion
meeting: Monthly on third Tuesdays of the month, at 7AM UTC (on Google Meet)
```

2021-04-23 06:52 UTC, techtrailhead approved these changes

2021-04-23 17:24 UTC, bwklein commented on content/en/working-group/glossaries.md
> +The goal of our community is to create a template for glossaries that can be easily integrated by anyone creating glossaries for their own project. The pilot will build processes and tools for the ge
```suggestion
The goal of our community is to create a template for glossaries that can be easily integrated by anyone creating glossaries for their own project.
The pilot will build processes and tools for the generic use case, developing and applying them within the geospatial mapping domain.
```

2021-04-23 17:24 UTC, bwklein approved these changes

2021-04-23 17:32 UTC, bwklein commented
@barbaricyawps It seems that all of @camerons changes have been incorporated.  I have re-requested a review from him to be sure.  Otherwise, it looks good to go.

2021-04-24 18:01 UTC, barbaricyawps commented
Merging this in!

2021-04-24 18:01 UTC, merged